#http://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html
#http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

#### Application Port설정
server:
  port: 8080
  servlet:    context-path: /study
---
#### Spring Boot Default Error Page
server:  error:    whitelabel:      enabled: false
---
#### CharacterEncodingFilter
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  datasource:
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:oracle:thin:@localhost:1521:xe
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: c##test_user1
    password: 1234
    initialization-mode: always    hikari: 
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  
  

 